In [6]:
import pandas as pd
import numpy as np
import openpyxl

In [7]:
df = pd.read_excel("Messy_Media_Campaign_dataset.xlsx")
df.head()

,Date,Campaign_Name,Theme,Channel,Sub_Channel,Communication_Objective,Audience,Vendor,Impressions,Clicks,Media_Cost,Production_Cost,Agency_Fee,Platform_Fee
0,2025-01-01,Winter Sale,Discounts,Digital,Facebook,Awareness,Adults,Meta,120000.0,2500,15000,2000.0,1000.0,500.0
1,01/02/2025,winter sale,discounts,Digital,Instagram,Awareness,adults,meta,130000.0,2700,16000,2100.0,1000.0,550.0
2,2025/03/01,Summer Launch,New Product,TV,NaN,Reach,All,Star TV,5000000.0,NaN,250000,15000.0,5000.0,0.0
3,2025-04-01,Summer Launch,New Product,tv,Prime Time,Reach,ALL,star tv,5100000.0,1000,255000,15000.0,5000.0,NaN
4,2025-05-01,Brand Campaign,Branding,OLV,Youtube,Consideration,Youth,Google,800000.0,12000,45000,5000.0,2500.0,1200.0

In [9]:
df.sample(5)

,Date,Campaign_Name,Theme,Channel,Sub_Channel,Communication_Objective,Audience,Vendor,Impressions,Clicks,Media_Cost,Production_Cost,Agency_Fee,Platform_Fee
5,05-06-2025,Brand Campaign,branding,OLV,YouTube,Consideration,youth,google,820000.0,12500,46000,5000.0,NaN,1250.0
10,2025-11-01,Diwali Sale,Festival,Digital,Instagram,Conversion,Adults,NaN,160000.0,3400,21000,2500.0,1200.0,700.0
6,2025-07-01,Festive Blast,Festival,Digital,Facebook,Conversion,Adults,Meta,NaN,3000,18000,2500.0,1200.0,600.0
7,2025-08-01,Festive Blast,Festival,Digital,facebook,Conversion,Adults,Meta,145000.0,abc,19000,2500.0,1200.0,650.0
13,2026-01-01,Republic Day,Patriotic,Radio,FM,Awareness,Adults,Radio Mirchi,250000.0,500,10000,1000.0,500.0,250.0

In [10]:
df.shape

(20, 14)

In [11]:
df.columns

Index(['Date', 'Campaign_Name', 'Theme', 'Channel', 'Sub_Channel',
       'Communication_Objective', 'Audience', 'Vendor', 'Impressions',
       'Clicks', 'Media_Cost', 'Production_Cost', 'Agency_Fee',
       'Platform_Fee'],
      dtype='str')

In [12]:
df.dtypes

Date                           str
Campaign_Name                  str
Theme                          str
Channel                        str
Sub_Channel                    str
Communication_Objective        str
Audience                       str
Vendor                         str
Impressions                float64
Clicks                         str
Media_Cost                   int64
Production_Cost            float64
Agency_Fee                 float64
Platform_Fee               float64
dtype: object

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Date                     20 non-null     str
 1   Campaign_Name            19 non-null     str
 2   Theme                    20 non-null     str
 3   Channel                  20 non-null     str
 4   Sub_Channel              19 non-null     str
 5   Communication_Objective  20 non-null     str
 6   Audience                 19 non-null     str
 7   Vendor                   19 non-null     str
 8   Impressions              19 non-null     float64
 9   Clicks                   19 non-null     str
 10  Media_Cost               20 non-null     int64
 11  Production_Cost          19 non-null     float64
 12  Agency_Fee               19 non-null     float64
 13  Platform_Fee             19 non-null     float64
dtypes: float64(4), int64(1), str(9)
memory usage: 2.3 KB

In [15]:
df.describe(include = 'all')

,Date,Campaign_Name,Theme,Channel,Sub_Channel,Communication_Objective,Audience,Vendor,Impressions,Clicks,Media_Cost,Production_Cost,Agency_Fee,Platform_Fee
count,20,19,20,20,19,20,19,19,1.900000e+01,19,20.000000,19.000000,19.000000,19.000000
unique,19,9,10,5,7,4,8,8,NaN,17,NaN,NaN,NaN,NaN
top,2026-01-01,Summer Launch,Festival,Digital,Instagram,Conversion,Adults,Meta,NaN,500,NaN,NaN,NaN,NaN
freq,2,4,6,12,9,8,8,9,NaN,2,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.249211e+06,NaN,47875.000000,4321.052632,1794.736842,744.736842
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.413832e+06,NaN,71068.327945,4028.727252,1322.654605,393.663257
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000e+04,NaN,10000.000000,1000.000000,500.000000,0.000000
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.525000e+05,NaN,18750.000000,2500.000000,1200.000000,575.000000
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.000000e+05,NaN,21750.000000,2500.000000,1200.000000,700.000000
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.100000e+05,NaN,45250.000000,5000.000000,1950.000000,800.000000
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.000000e+06,NaN,255000.000000,15000.000000,5000.000000,1500.000000

In [16]:
#Null Analysis
df.isnull().sum()

Date                       0
Campaign_Name              1
Theme                      0
Channel                    0
Sub_Channel                1
Communication_Objective    0
Audience                   1
Vendor                     1
Impressions                1
Clicks                     1
Media_Cost                 0
Production_Cost            1
Agency_Fee                 1
Platform_Fee               1
dtype: int64

In [19]:
Percentage_null = (df.isnull().sum()/len(df))*100
Percentage_null

Date                       0.0
Campaign_Name              5.0
Theme                      0.0
Channel                    0.0
Sub_Channel                5.0
Communication_Objective    0.0
Audience                   5.0
Vendor                     5.0
Impressions                5.0
Clicks                     5.0
Media_Cost                 0.0
Production_Cost            5.0
Agency_Fee                 5.0
Platform_Fee               5.0
dtype: float64

In [20]:
#Duplicate Analysis
df.duplicated().sum()

np.int64(1)

In [21]:
df[df.duplicated()]

,Date,Campaign_Name,Theme,Channel,Sub_Channel,Communication_Objective,Audience,Vendor,Impressions,Clicks,Media_Cost,Production_Cost,Agency_Fee,Platform_Fee
13,2026-01-01,Republic Day,Patriotic,Radio,FM,Awareness,Adults,Radio Mirchi,250000.0,500,10000,1000.0,500.0,250.0

In [22]:
#unique Values
df.nunique()

Date                       19
Campaign_Name               9
Theme                      10
Channel                     5
Sub_Channel                 7
Communication_Objective     4
Audience                    8
Vendor                      8
Impressions                17
Clicks                     17
Media_Cost                 17
Production_Cost             8
Agency_Fee                  8
Platform_Fee               12
dtype: int64

In [24]:
Percentage_unique = (df.nunique()/len(df))*100
Percentage_unique

Date                       95.0
Campaign_Name              45.0
Theme                      50.0
Channel                    25.0
Sub_Channel                35.0
Communication_Objective    20.0
Audience                   40.0
Vendor                     40.0
Impressions                85.0
Clicks                     85.0
Media_Cost                 85.0
Production_Cost            40.0
Agency_Fee                 40.0
Platform_Fee               60.0
dtype: float64

In [26]:
df['Channel'].value_counts()

Channel
Digital    12
OLV         4
Radio       2
TV          1
tv          1
Name: count, dtype: int64

In [29]:
#Data Cleaning
#Audience - removing leading and trailing spaces
df['Audience'] = df['Audience'].str.strip()

In [30]:
obj_cols = df.select_dtypes(include = 'object').columns
df[obj_cols] = df[obj_cols].apply(lambda x:x.str.strip())

/var/folders/sl/ylx38ztj4wn7n_b5mssc94kr0000gn/T/ipykernel_29863/126451047.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  obj_cols = df.select_dtypes(include = 'object').columns

In [31]:
df.head()

,Date,Campaign_Name,Theme,Channel,Sub_Channel,Communication_Objective,Audience,Vendor,Impressions,Clicks,Media_Cost,Production_Cost,Agency_Fee,Platform_Fee
0,2025-01-01,Winter Sale,Discounts,Digital,Facebook,Awareness,Adults,Meta,120000.0,2500,15000,2000.0,1000.0,500.0
1,01/02/2025,winter sale,discounts,Digital,Instagram,Awareness,adults,meta,130000.0,2700,16000,2100.0,1000.0,550.0
2,2025/03/01,Summer Launch,New Product,TV,NaN,Reach,All,Star TV,5000000.0,NaN,250000,15000.0,5000.0,0.0
3,2025-04-01,Summer Launch,New Product,tv,Prime Time,Reach,ALL,star tv,5100000.0,1000,255000,15000.0,5000.0,NaN
4,2025-05-01,Brand Campaign,Branding,OLV,Youtube,Consideration,Youth,Google,800000.0,12000,45000,5000.0,2500.0,1200.0

In [34]:
df.columns = df.columns.str.lower().str.strip()

In [35]:
df['channel'].value_counts()

channel
Digital    12
OLV         4
Radio       2
TV          1
tv          1
Name: count, dtype: int64